// Booking model — the heart of the app.
// We snapshot the service details at booking-time so price/name changes later don't rewrite history.

import mongoose from "mongoose";

// Embedded service snapshot
const bookingServiceSchema = new mongoose.Schema(
  {
    service: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Service",
      required: true,
    },
    name: { type: String, required: true },
    price: { type: Number, required: true },
    duration: { type: Number, required: true }, // minutes
  },
  { _id: false },
);

const bookingSchema = new mongoose.Schema(
  {
    bookingId: {
      type: String,
      required: true,
      unique: true,
      // generated by utils/bookingId.util.js — e.g. "GH-A3X9P2"
    },

    customer: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: true,
    },
    // Snapshot of customer details at booking time (handy for emails / walk-ins)
    customerName: { type: String, required: true },
    customerEmail: { type: String, required: true },
    customerPhone: { type: String, default: "" },

    services: { type: [bookingServiceSchema], required: true },

    stylist: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Stylist",
      required: true,
    },
    stylistName: { type: String, required: true },

    // Date is the calendar day (00:00 local). startTime/endTime are full datetimes.
    date: { type: Date, required: true },
    startTime: { type: Date, required: true },
    endTime: { type: Date, required: true },
    totalDuration: { type: Number, required: true }, // minutes
    totalAmount: { type: Number, required: true }, // after promo discount

    // Promo discount tracking
    promoCode: { type: String, default: "" },
    discountAmount: { type: Number, default: 0 },

    status: {
      type: String,
      enum: ["pending", "confirmed", "completed", "cancelled"],
      default: "pending",
    },
    cancellationReason: { type: String, default: "" },
    notes: { type: String, default: "" }, // admin notes

    payment: { type: mongoose.Schema.Types.ObjectId, ref: "Payment" },

    // True for admin-created walk-in / phone bookings (manual cash payment)
    isWalkIn: { type: Boolean, default: false },

    // For 24-hour reminder cron — flips true once we send the reminder
    reminderSent: { type: Boolean, default: false },
  },
  { timestamps: true },
);

// Composite index — finding a stylist's bookings on a given date is the
// single hottest query in the app (slot-availability calculation).
bookingSchema.index({ stylist: 1, date: 1 });
bookingSchema.index({ customer: 1, createdAt: -1 });

const Booking = mongoose.model("Booking", bookingSchema);
export default Booking;
